### PR TITLE
Fix the bot

### PR DESCRIPTION
**Pull request by Ast3risk-ops**
Full fix Omar.

### CODE REVIEW

**Comment by Ast3risk-ops** [comment]
You'll wanna change NQN's prefix if you apply these changes.

**Comment by SteavenGamerYT** [comment]
sorry we cant accept that since it breaks the bot not fixs it

**Comment by Ast3risk-ops** [comment]
> sorry we cant accept that since it breaks the bot not fixs it

Nope I checked the bot still works, I'd say it makes the bot better and a lot of people would agree

**Comment by SteavenGamerYT** [comment]
no one have confirmed that yet for me

**Comment by Ast3risk-ops** [comment]
> no one have confirmed that yet for me

then make a dev version of the bot and test that

**Comment by SteavenGamerYT** [comment]
BRO SFTU I HAVE MADE /adhminhelp into real / command

**Pull request closed without merging**
